notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

language: ruby

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t methpipe .
 - docker images | grep -c methpipe
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm methpipe nextflow -v
 - docker run -t --rm methpipe runMethPipe.sh
